---
title: Jsonlovesyaml
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: JsonLovesYaml
description: " JsonLovesYaml is a collecton of Tutorials | Musings | Podcasts | Design
  Patterns for the Cloud Native "
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/jsonlovesyaml"
disqus: jsonlovesyaml
email: vamsi.ramakrishnan@oracle.com
mailchimp-list: https://mailchi.mp/8c069e177357/jsonlovesyaml
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
- jekyll-menus
authors:
  vamsi:
    name: Vamsi
    site: https://in.linkedin.com/in/vamsiramakrishnan
    avatar: "/assets/images/avatar1.jpg"
    bio: Delighting Enterprise Customers with elegantly architected solutions on Oracle
      Cloud.
    email: vamsi.ramakrishnan@oracle.com
    twitter: https://twitter.com/mrvemzi
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
