# Site
name: 'JsonLovesYaml'
description: ' JsonLovesYaml is a collecton of Tutorials | Musings | Podcasts | Design Patterns for the Cloud Native '
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/jsonlovesyaml'
disqus: 'jsonlovesyaml'
email: 'vamsi.ramakrishnan@oracle.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    vamsi:
      name:           Vamsi
      site:           https://in.linkedin.com/in/vamsiramakrishnan
      avatar:         /assets/images/avatar1.jpg
      bio:            "A pre-sales consultant with 8 years of pre-sales and product-development experience in the automotive embedded | cloud computing industry. I currently work as a senior solutions consultant at Oracle. I specialise in architecting best of breed cloud native, private and public cloud solutions for enterprise BFSI ( Banking Financial Sector and Insurance ) customers in Mumbai. I work as a Key account solution engineer from Oracle for a leading private bank. I started my career at Bosch working on embedded systems technology that powered the drivetrain of electric vehicles of the world's leading automaker, I had the opportunity to work on several functional tasks in the SDLC of Electric Powertrain ECUs during this three and a half year stint. I spent considerable amount of this time in modelling and simulation / building a digital twin. The next three and a half years I spent advocating Advanced Measurement, Calibration, Automotive IoT, Advanced Driver Assistance, Big Data Solutions from the mature markets to leading Indian car makers and automotive technology providers in the emerging markets. This stint helped me discover my passion for working with customers. It also allowed me to learn about automotive big data pipelines / lakes , GPUs/cloud computing for deep learning and computer vision in autonomous driving. I worked on a nanodegree program by udacity that allowed me to venture into new avenues like data science , realize it’s value first hand as to how it would be an essential part of the solution for problems of the future. When I get the time I read extensively about DevOps, CNCF, High-Performance Computing, Deep Learning with Convolutional Neural Nets."
      email:          vamsi.ramakrishnan@oracle.com
      twitter:        https://twitter.com/mrvemzi
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
